from .constants import (
    LARGURA, ALTURA,
    FPS,
    PRETO, BRANCO, CIANO, MAGENTA, AMARELO, VERMELHO,
    BOLA_RAIO, BOLA_VEL_X, BOLA_VEL_Y,
    RAQUETE_LARGURA, RAQUETE_ALTURA, RAQUETE_VEL, RAQUETE_Y,
    BLOCO_LINHAS, BLOCO_COLUNAS,
    BLOCO_LARGURA, BLOCO_ALTURA,
    BLOCO_ESPACO_X, BLOCO_ESPACO_Y,
    BLOCO_OFFSET_X, BLOCO_OFFSET_Y,
    BLOCO_PONTOS,
)
